/* tslint:disable */
/* eslint-disable */
/**
 * ForwardChess API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Book,
  GetBookRequest,
} from '../models';
import {
    BookFromJSON,
    BookToJSON,
    GetBookRequestFromJSON,
    GetBookRequestToJSON,
} from '../models';

export interface GetBookOperationRequest {
    email: string;
    authorization: string;
    getBookRequest?: GetBookRequest;
}

export interface GetBookFileRequest {
    bookId: string;
    file: string;
    t: string;
    d: string;
}

export interface GetBookFileListRequest {
    bookId: string;
    sample?: boolean;
}

export interface GetBookSimpleRequest {
    bookId: string;
}

/**
 * 
 */
export class BookApi extends runtime.BaseAPI {

    /**
     */
    async getAllBooksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Book>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/books/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookFromJSON));
    }

    /**
     */
    async getAllBooks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Book>> {
        const response = await this.getAllBooksRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getBookRaw(requestParameters: GetBookOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Book>> {
        if (requestParameters.email === null || requestParameters.email === undefined) {
            throw new runtime.RequiredError('email','Required parameter requestParameters.email was null or undefined when calling getBook.');
        }

        if (requestParameters.authorization === null || requestParameters.authorization === undefined) {
            throw new runtime.RequiredError('authorization','Required parameter requestParameters.authorization was null or undefined when calling getBook.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.authorization !== undefined && requestParameters.authorization !== null) {
            headerParameters['Authorization'] = String(requestParameters.authorization);
        }

        const response = await this.request({
            path: `/api/books/validation/{email}`.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters.email))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetBookRequestToJSON(requestParameters.getBookRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookFromJSON(jsonValue));
    }

    /**
     */
    async getBook(requestParameters: GetBookOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Book> {
        const response = await this.getBookRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getBookFileRaw(requestParameters: GetBookFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.bookId === null || requestParameters.bookId === undefined) {
            throw new runtime.RequiredError('bookId','Required parameter requestParameters.bookId was null or undefined when calling getBookFile.');
        }

        if (requestParameters.file === null || requestParameters.file === undefined) {
            throw new runtime.RequiredError('file','Required parameter requestParameters.file was null or undefined when calling getBookFile.');
        }

        if (requestParameters.t === null || requestParameters.t === undefined) {
            throw new runtime.RequiredError('t','Required parameter requestParameters.t was null or undefined when calling getBookFile.');
        }

        if (requestParameters.d === null || requestParameters.d === undefined) {
            throw new runtime.RequiredError('d','Required parameter requestParameters.d was null or undefined when calling getBookFile.');
        }

        const queryParameters: any = {};

        if (requestParameters.t !== undefined) {
            queryParameters['t'] = requestParameters.t;
        }

        if (requestParameters.d !== undefined) {
            queryParameters['d'] = requestParameters.d;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/gcs/forwardchess-books/{bookId}/{file}`.replace(`{${"bookId"}}`, encodeURIComponent(String(requestParameters.bookId))).replace(`{${"file"}}`, encodeURIComponent(String(requestParameters.file))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async getBookFile(requestParameters: GetBookFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getBookFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getBookFileListRaw(requestParameters: GetBookFileListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters.bookId === null || requestParameters.bookId === undefined) {
            throw new runtime.RequiredError('bookId','Required parameter requestParameters.bookId was null or undefined when calling getBookFileList.');
        }

        const queryParameters: any = {};

        if (requestParameters.sample !== undefined) {
            queryParameters['sample'] = requestParameters.sample;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/books/{bookId}/list`.replace(`{${"bookId"}}`, encodeURIComponent(String(requestParameters.bookId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getBookFileList(requestParameters: GetBookFileListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getBookFileListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getBookSimpleRaw(requestParameters: GetBookSimpleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Book>> {
        if (requestParameters.bookId === null || requestParameters.bookId === undefined) {
            throw new runtime.RequiredError('bookId','Required parameter requestParameters.bookId was null or undefined when calling getBookSimple.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/books/{bookId}`.replace(`{${"bookId"}}`, encodeURIComponent(String(requestParameters.bookId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookFromJSON(jsonValue));
    }

    /**
     */
    async getBookSimple(requestParameters: GetBookSimpleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Book> {
        const response = await this.getBookSimpleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
