/* tslint:disable */
/* eslint-disable */
/**
 * ForwardChess API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAccountsResetPasswordPostRequest
 */
export interface ApiAccountsResetPasswordPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiAccountsResetPasswordPostRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiAccountsResetPasswordPostRequest
     */
    deviceId?: string;
}

/**
 * Check if a given object implements the ApiAccountsResetPasswordPostRequest interface.
 */
export function instanceOfApiAccountsResetPasswordPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiAccountsResetPasswordPostRequestFromJSON(json: any): ApiAccountsResetPasswordPostRequest {
    return ApiAccountsResetPasswordPostRequestFromJSONTyped(json, false);
}

export function ApiAccountsResetPasswordPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAccountsResetPasswordPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'deviceId': !exists(json, 'deviceId') ? undefined : json['deviceId'],
    };
}

export function ApiAccountsResetPasswordPostRequestToJSON(value?: ApiAccountsResetPasswordPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'deviceId': value.deviceId,
    };
}

